from pathlib import Path

##############################
# Globals
##############################

PROJECT_DIR = Path(".").absolute()
PROJECT_NAME = "telomeres"

workdir: PROJECT_DIR

configfile: Path("config/config.yml")

##############################
# Includes
##############################

include: "src/snakemake/hg38_telomere_coords.smk"
#include: "src/snakemake/bamprep.smk"
#include: "src/snakemake/mosdepth.smk"
#include: "src/snakemake/multimapping.smk"
#include: "src/snakemake/stats.smk"
#include: "src/snakemake/telomerecat.smk"
#include: "src/snakemake/igv.smk"
    
##############################
# Project rules
##############################
RESULT_FILES = ["data/processed/telomere_coords.bed"]

rule all:
    """Default rule to generate final report/results"""
    input: RESULT_FILES

    