from pathlib import Path

##############################
# Globals
##############################

PROJECT_DIR = Path(".").absolute()
PROJECT_NAME = "telomeres"

workdir: PROJECT_DIR

configfile: Path("config/config.yml")
    
##############################
# Project rules
##############################
RESULT_FILES = []

rule all:
    """Default rule to generate final report/results"""
    input: RESULT_FILES
    output: "summary.txt"
    shell:
        "ls results"

##############################
# Includes
##############################
#include: "src/snakemake/hg38_telomere_coords.smk"
#include: "src/snakemake/bamprep.smk"
#include: "src/snakemake/multimapping.smk"
#include: "src/snakemake/stats.smk"
#include: "src/snakemake/telomerecat.smk"
#include: "src/snakemake/igv.smk"